package dlms;


/**
* dlms/FrontEndOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndOperations.idl
* Friday, March 29, 2019 1:07:09 PM EDT
*/

public interface FrontEndOperationsOperations 
{
  String borrowItem (String userId, String itemId, int noOfDays);
  String findItem (String userId, String itemName);
  String returnItem (String userId, String itemId);
  String exchangeItem (String userId, String newItemId, String oldItemId);
  String addItem (String managerId, String itemId, String itemName, int quantity);
  String removeItem (String managerId, String itemId, int quantity);
  String listItemAvailability (String managerId);
} // interface FrontEndOperationsOperations
