package dlms;


/**
* dlms/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndOperations.idl
* Friday, March 29, 2019 1:07:09 PM EDT
*/

public interface FrontEndOperations extends FrontEndOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndOperations
