package dlms;

/**
* dlms/FrontEndOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndOperations.idl
* Wednesday, March 20, 2019 12:51:12 AM EDT
*/

public final class FrontEndOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public dlms.FrontEndOperations value = null;

  public FrontEndOperationsHolder ()
  {
  }

  public FrontEndOperationsHolder (dlms.FrontEndOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dlms.FrontEndOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dlms.FrontEndOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dlms.FrontEndOperationsHelper.type ();
  }

}
