package dlms;


/**
* dlms/FrontEndOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndOperations.idl
* Wednesday, March 20, 2019 12:51:12 AM EDT
*/

public interface FrontEndOperationsOperations 
{
  String borrowItem (String userId, String itemId, int noOfDays);
  String findItem (String userId, String itemName);
  boolean returnItem (String userId, String itemId);
  boolean exchangeItem (String userId, String newItemId, String oldItemId);
  boolean addItem (String managerId, String itemId, String itemName, int quantity);
  boolean removeItem (String managerId, String itemId, int quantity);
  String listItemAvailability (String managerId);
} // interface FrontEndOperationsOperations
