package dlms;


/**
* dlms/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndOperations.idl
* Wednesday, March 20, 2019 12:51:12 AM EDT
*/

public interface FrontEndOperations extends FrontEndOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndOperations
