package dlms;


/**
* dlms/FrontEndOperationsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndOperations.idl
* Friday, March 29, 2019 1:07:09 PM EDT
*/

public abstract class FrontEndOperationsPOA extends org.omg.PortableServer.Servant
 implements dlms.FrontEndOperationsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("borrowItem", new java.lang.Integer (0));
    _methods.put ("findItem", new java.lang.Integer (1));
    _methods.put ("returnItem", new java.lang.Integer (2));
    _methods.put ("exchangeItem", new java.lang.Integer (3));
    _methods.put ("addItem", new java.lang.Integer (4));
    _methods.put ("removeItem", new java.lang.Integer (5));
    _methods.put ("listItemAvailability", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dlms/FrontEndOperations/borrowItem
       {
         String userId = in.read_string ();
         String itemId = in.read_string ();
         int noOfDays = in.read_long ();
         String $result = null;
         $result = this.borrowItem (userId, itemId, noOfDays);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // dlms/FrontEndOperations/findItem
       {
         String userId = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (userId, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // dlms/FrontEndOperations/returnItem
       {
         String userId = in.read_string ();
         String itemId = in.read_string ();
         String $result = null;
         $result = this.returnItem (userId, itemId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // dlms/FrontEndOperations/exchangeItem
       {
         String userId = in.read_string ();
         String newItemId = in.read_string ();
         String oldItemId = in.read_string ();
         String $result = null;
         $result = this.exchangeItem (userId, newItemId, oldItemId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // dlms/FrontEndOperations/addItem
       {
         String managerId = in.read_string ();
         String itemId = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.addItem (managerId, itemId, itemName, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // dlms/FrontEndOperations/removeItem
       {
         String managerId = in.read_string ();
         String itemId = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.removeItem (managerId, itemId, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // dlms/FrontEndOperations/listItemAvailability
       {
         String managerId = in.read_string ();
         String $result = null;
         $result = this.listItemAvailability (managerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dlms/FrontEndOperations:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FrontEndOperations _this() 
  {
    return FrontEndOperationsHelper.narrow(
    super._this_object());
  }

  public FrontEndOperations _this(org.omg.CORBA.ORB orb) 
  {
    return FrontEndOperationsHelper.narrow(
    super._this_object(orb));
  }


} // class FrontEndOperationsPOA
