package dlms;


/**
* dlms/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndOperations.idl
* Monday, April 1, 2019 10:58:05 PM EDT
*/

public interface FrontEndOperations extends FrontEndOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEndOperations
